# Generated by Django 2.2.3 on 2019-07-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='nomor_absen',
            field=models.IntegerField(),
        ),
    ]
