# Generated by Django 2.2.3 on 2019-07-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='jadwal_praktik',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3),
        ),
    ]
