# Generated by Django 2.2.3 on 2019-07-22 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0002_auto_20190722_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokter',
            old_name='jadwal_praktik',
            new_name='hari_praktik',
        ),
        migrations.AddField(
            model_name='dokter',
            name='jam_praktik',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
